dist: xenial
sudo: required
language: python
python:
  - "2.6"
  - "2.7.14"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install pytest pytest-cov
  - pip install coveralls
  
script:
  - python test_palindromes.py 
  - pylint palindromes.py
  - pycodestyle --cov=.
  - coverage report
 
after_success:
    coveralls